from importlib import reload
from logging import Logger

import alertsActor.utils.key as keyUtils
import ics.utils.time as pfsTime
from opscore.actor.keyvar import KeyVar
from subaru.sts.client.radio import Radio

reload(keyUtils)


class KeyCallback:
    """Keyword callback, note that a keyword can have several fields."""

    def __init__(self, actorRules, keyVarName, stsMaps) -> None:
        self.actorRules = actorRules
        self.keyVarName = keyVarName
        self.keys = dict([(stsMap["keyId"], keyUtils.Key(self, **stsMap)) for stsMap in stsMaps])

    @property
    def logger(self) -> Logger:
        """Return the logger from actorRules."""
        return self.actorRules.logger

    @property
    def fromStsId(self) -> dict[int, keyUtils.Key]:
        """Return a dictionary of keys indexed by their STS ID."""
        return dict([(key.stsKey.stsId, key) for key in self.keys.values()])

    @property
    def fromKeyName(self) -> dict[str, keyUtils.Key]:
        """Return a dictionary of keys indexed by their keyword name."""
        return dict([(key.mhsKey.keyName, key) for key in self.keys.values()])

    def __call__(self, keyVar: KeyVar, newValue: bool = True) -> None:
        """This function is called when new keys are received by the dispatcher.

        Parameters
        ----------
        keyVar : `opscore.protocols.keys.KeyVar`
            The keyword variable that was updated.
        newValue : `bool`
            Whether this is a new value or just a periodic update.
        """
        buffer = []

        values = keyVar.getValue(doRaise=False)
        values = values if isinstance(values, tuple) else [values]

        # if keyvar is not genuine (eg not generated by the actor), the associated timestamp is not correct.
        if (
            not keyVar.isGenuine
            and (pfsTime.timestamp() - keyVar.timestamp) < self.actorRules.actor.actorConfig["STS_DATA_RATE"]
        ):
            return

        for keyId, key in self.keys.items():
            # convert timestamp and value to a valid alert-compliant STS datum."""
            datum = key.toStsDatum(keyVar.timestamp, values[keyId], newValue=newValue)
            # assess whether it needs to be transmitted or not.
            doSend = key.doTransmit(datum)
            # avoid filling logs unnecessarily.
            if newValue or doSend:
                self.logger.debug(
                    f"updating(doSend={doSend}) STSid {key.stsKey.stsId}({key.stsKey.stsType}) "
                    f"from {keyVar.actor}.{keyVar.name}[{keyId}] with ({datum.value[0]}, {datum.value[1]})"
                )
            if doSend:
                key.genKey(datum)
                buffer.append(datum)

        self.transmit(buffer, stsHost=self.actorRules.actor.stsHost)

    def transmit(self, buffer: list, stsHost: str) -> None:
        """Transmit datum and clear buffer.

        Parameters
        ----------
        buffer : `list`
            List of STS datums to transmit.
        stsHost : `str`
            The STS host to transmit to.
        """
        if not buffer:
            return

        self.logger.debug(f"flushing STS (host={stsHost}), with: {buffer}")
        stsServer = Radio(host=stsHost)
        stsServer.transmit(buffer)

        # record transmitted datums.
        for datum in buffer:
            self.fromStsId[datum.id].transmitted = datum

        # generate overall alertStatus keyword
        self.actorRules.actor.genAlertStatus()

    def identify(self, identifier: str | None) -> list[keyUtils.Key]:
        """Return iterable of keys matching the given identifier.

        Parameters
        ----------
        identifier : `str` | `None`
            The identifier to match (either keyId or keyName).

        Returns
        -------
        keys : `list` [ `keyUtils.Key` ]
            List of matching keys.
        """
        # return all keys in that case.
        if identifier is None:
            return list(self.keys.values())

        if identifier.isdigit():
            # identifier is mhs keyId.
            key = self.keys[int(identifier)]
        else:
            # identifier must be mhs keyName.
            key = self.fromKeyName[identifier]

        # always returns an iterable object.
        return [key]
