################################################################
#
# Actual alerts below
#

# We group all keyword alerts by actor
#
_alert: &ALERT
  limits: [null, null]

vis: &VIS
  offline:
    null
  standby:
    null
  pumpdown:
    turboSpeed[0]:
      <<: *ALERT
      limits: [89000, null]
    pressure[0]:
      <<: *ALERT
      limits: [null, 1]
  cooldown:
    coolerTemps[1]:
      <<: *ALERT
      limits: [null, 45]
    coolerTemps[3]:
      <<: *ALERT
      limits: [70, null]
    pressure[0]:
      <<: *ALERT
      limits: [null, 5.0e-6]
  operation:
    coolerTemps[1]:
      <<: *ALERT
      limits: [null, 35]
    coolerTemps[3]:
      <<: *ALERT
      limits: [70, null]
    pressure[0]:
      <<: *ALERT
      limits: [null, 5.0e-6]
    visTemps[5]:
      <<: *ALERT
      limits: [null, 164]
    visTemps[6]:
      <<: *ALERT
      limits: [null, 164]
  warmup:
    null
  bakeout:
    turboSpeed[0]:
      <<: *ALERT
      limits: [89000, null]
    visTemps[5]:
      <<: *ALERT
      limits: [null, 330]
    visTemps[6]:
      <<: *ALERT
      limits: [null, 330]
  unknown:
    null


nir: &NIR
  off:
    null
  standby:
    null
  pumpdown:
    coolerTemps[2]:
      <<: *ALERT
      limits: [null, 40]
    pressure[0]:
      <<: *ALERT
      limits: [null, 2.0e-6]
  cooldown:
    coolerTemps[2]:
      <<: *ALERT
      limits: [null, 40]
    pressure[0]:
      <<: *ALERT
      limits: [null, 2.0e-6]

  operation:
    coolerTemps[2]:
      <<: *ALERT
      limits: [null, 40]
    pressure[0]:
      <<: *ALERT
      limits: [null, 1.0e-6]
  warmup:
    pressure[0]:
      <<: *ALERT
      limits: [null, 1.0e-6]
  bakeout:
    null
  unknown:
    null

xcu_n1:
  <<: *NIR
xcu_n2:
  <<: *NIR
xcu_n3:
  <<: *NIR
xcu_n4:
  <<: *NIR

xcu_b1:
  <<: *VIS
xcu_b2:
  <<: *VIS
xcu_b3:
  <<: *VIS
xcu_b4:
  <<: *VIS

xcu_r1:
  <<: *VIS
xcu_r2:
  <<: *VIS
xcu_r3:
  <<: *VIS
xcu_r4:
  <<: *VIS

# JHU Optics lab
xcu_n8:
  <<: *NIR
xcu_r8:
  <<: *VIS
