# Template for all keyword alerts:
#    alertType: a name, to help any consumers
#    call: True, False, or an object, method pair, where we find the named object
#          and call the corresponding method.
#          If True, call a generic callback for this alertType
#    alertFmt: if non-null, an f-string evaluated inside the call method. It is expected
#              to have the alertCall() argument variables available to it, plus "value".
#              This may be the biggest security hole ever put into a program.
#
# The call method is called with:
#    alertCall(fullReply, actorName, keyName, keyIndex)
#
# Note that the base template "alert" is actually a trigger: it is always called
# when a new keyword value is received.
#
_alert: &ALERT
  alertType: trigger
  call: True
  alertFmt: null
# Template for an alert with simple limits:
#   limits: a numeric pair of non-inclusive limits, with NaN for
#           unused limits. I.e. trigger if (min <= val or val >=  max)
#
_limitsAlert: &LIMITS_ALERT
  <<: *ALERT
  alertType: limits
  limits: [null, null]

# Template for regexp match alerts:
#   re: a regular expression
#   invert: bool, whether or not to invert the match sense
#
_regexpAlert: &REGEXP_ALERT
  <<: *ALERT
  alertType: regexp
  pattern: null
  invert: False

################################################################
#
# Actual alerts below
#

# We group all keyword alerts by actor
#
actors:
  charis:                       # Just for pre-commissioning testing
    temps[0]:
      <<: *LIMITS_ALERT
      limits: [null, 40.9]
    temps:
      <<: *ALERT
      call: charis.checkTempRange
    motor6status[6]:
      <<: *REGEXP_ALERT
      pattern: 'limit switch error'

  meb:                          # MCS E-Box
    flow:
      <<: *LIMITS_ALERT
      limits: [0.0, null]
      alertFmt: 'coolant flow has stopped'
    temps[0]:
      <<: *LIMITS_ALERT
      limits: [10.0, 25.0]
      alertFmt: 'temperature out of range'

  xcu_{cam}:                    # All XCUs
    pcmPower1[2]:
      <<: *LIMITS_ALERT
      limits: [27, null]
      alertFmt: '24V-UPS Input power is failing!!: {value}V'
    pcmPower2[2]:
      <<: *LIMITS_ALERT
      limits: [24, null]
      alertFmt: '24V-AUX Input power is failing!!: {value}V'
    pressure[0]:
      <<: *LIMITS_ALERT
      limits: [1e-10, 1e-02]
      alertFmt: 'Ion gauge pressure is out of range!!: {value} Torr'
    turboSpeed[0]:
      <<: *LIMITS_ALERT
      limits: [89000, null]
      alertFmt: 'Turbo speed is too low!!: {value}RPM'
    ionpump1[4]:
      <<: *LIMITS_ALERT
      limits: [1e-10, 1e-05]
      alertFmt: 'Ionpump 1 pressure is out of range!!: {value}Torr'
    ionpump2[4]:
      <<: *LIMITS_ALERT
      limits: [1e-10, 1e-05]
      alertFmt: 'Ionpump 2 pressure is out of range!!: {value}Torr'
    coolerTemps[1]:
      <<: *LIMITS_ALERT
      limits: [null, 32]
      alertFmt: 'Cooler reject is too high!!: {value}C'
    coolerTemps[3]:
      <<: *LIMITS_ALERT
      limits: [69, null]
      alertFmt: 'Cooler power is failing!!: {value}W'
    heaters[4]:
      <<: *LIMITS_ALERT
      limits: [0, null]
      alertFmt: 'CCD heater should be on !!: {value}'
    temps:
      <<: *ALERT
      call: xcu.checkTempRange

  enu_{smId}:
    temps1:
      <<: *ALERT
      call: enu.checkTempRange
    temps2:
      <<: *ALERT
      call: enu.checkTempRange

  tests:
    keytest1:
      <<: *ALERT
      call: tests.checkTempRange
    keytest2[1]:
      <<: *LIMITS_ALERT
      limits: [0, 30]
      alertFmt: 'keytest2 is out of range !!: {value}'
    keytest3:
      <<: *LIMITS_ALERT
      limits: [null, 1e-06]
      alertFmt: 'keytest3 is too high!!: {value}'
