actors:
  meb:
    temps: [[0, 1096],        # Get rid of the CHARIS hack below before using.
            [1, 1097],
            [2, 1098],
            [3, 1099],
            [4, 1100],
            [5, 1101],
            [6, 1102]]
    power:
      [[0, 1103],
       [1, 1104],
       [2, 1105],
       [3, 1106]]
    flow: [[0, 1107]]

  dcb:
    atenVAW:
      [[0, 1108],
       [1, 1109],
       [2, 1110]]

  xcu_b1:
    coolerLoop:
      [[0, 1120]]
    coolerTemps:
      [[0, 1121],
       [1, 1122],
       [2, 1123],
       [3, 1124]]
    pressure:
      [[0, 1125]]
    ionpump1:
      [[0, 1126],
       [4, 1127]]
    ionpump2:
      [[0, 1128],
       [4, 1129]]
    pcmPower1:
      [[2, 1130]]
    pcmPower2:
      [[2, 1131]]
    temps:
      [[0, 1132],
       [1, 1133],
       [2, 1134],
       [3, 1135],
       [4, 1136],
       [10, 1137],
       [11, 1138]]
    heaters:
      [[4, 1139],
       [5, 1140],
       [6, 1141],
       [7, 1142]]
    gatevalve:
      [[0, 1143],
       [1, 1144]]
    turboSpeed:
      [[0, 1145]]

  xcu_r1:
    coolerLoop:
      [[0, 1150]]
    coolerTemps:
      [[0, 1151],
       [1, 1152],
       [2, 1153],
       [3, 1154]]
    pressure:
      [[0, 1155]]
    ionpump1:
      [[0, 1156],
       [4, 1157]]
    ionpump2:
      [[0, 1158],
       [4, 1159]]
    pcmPower1:
      [[2, 1160]]
    pcmPower2:
      [[2, 1161]]
    temps:
      [[0, 1162],
       [1, 1163],
       [2, 1164],
       [3, 1165],
       [4, 1166],
       [10, 1167],
       [11, 1168]]
    heaters:
      [[4, 1169],
       [5, 1170],
       [6, 1171],
       [7, 1172]]
    gatevalve:
      [[0, 1173],
       [1, 1174]]
    turboSpeed:
      [[0, 1175]]

  enu_sm1:
    temps1:
      [[0, 1180],
       [1, 1181],
       [2, 1182],
       [3, 1183],
       [4, 1184],
       [5, 1185],
       [6, 1186],
       [7, 1187],
       [8, 1188],
       [9, 1189]]
    temps2:
      [[0, 1190],
       [1, 1191],
       [2, 1192],
       [3, 1193],
       [4, 1194],
       [5, 1195],
       [6, 1196],
       [7, 1197],
       [8, 1198]]
  tests:
    keytest1:
      [[0, 2010],
       [1, 2011],
       [2, 2012]]
    keytest2:
      [[0, 2013],
       [1, 2014]]
    keytest3:
      [[0, 2015]]





#  mcs:
#    ccdTemp: [[0, 1108]]

# 1096, "FLOAT+TEXT", "PFS: MCS MEB Temp 1"
# 1097, "FLOAT+TEXT", "PFS: MCS MEB Temp 2"
# 1098, "FLOAT+TEXT", "PFS: MCS MEB Temp 3"
# 1099, "FLOAT+TEXT", "PFS: MCS MEB Temp 4"
# 1100, "FLOAT+TEXT", "PFS: MCS MEB Temp 5"
# 1101, "FLOAT+TEXT", "PFS: MCS MEB Temp 6"
# 1102, "FLOAT+TEXT", "PFS: MCS MEB Temp 7"
# 1103, "INTEGER+TEXT", "PFS: MCS MEB Power 1"
# 1104, "INTEGER+TEXT", "PFS: MCS MEB Power 2"
# 1105, "INTEGER+TEXT", "PFS: MCS MEB Power 3"
# 1106, "INTEGER+TEXT", "PFS: MCS MEB Power 4"
# 1107, "FLOAT+TEXT", "PFS: MCS MEB Flow"
# 1108, "FLOAT+TEXT", "PFS: MCS MCS CCD Temp"
