actors:
  meb:
    temps: [[0, 1096],        # Get rid of the CHARIS hack below before using.
            [1, 1097],
            [2, 1098],
            [3, 1099],
            [4, 1100],
            [5, 1101],
            [6, 1102]]
    power:
      [[0, 1103],
       [1, 1104],
       [2, 1105],
       [3, 1106]]
    flow: [[0, 1107]]

  dcb:
    atenVAW:
      [[0, 1108],
       [1, 1109],
       [2, 1110]]

#  mcs:
#    ccdTemp: [[0, 1108]]

# 1096, "FLOAT+TEXT", "PFS: MCS MEB Temp 1"
# 1097, "FLOAT+TEXT", "PFS: MCS MEB Temp 2"
# 1098, "FLOAT+TEXT", "PFS: MCS MEB Temp 3"
# 1099, "FLOAT+TEXT", "PFS: MCS MEB Temp 4"
# 1100, "FLOAT+TEXT", "PFS: MCS MEB Temp 5"
# 1101, "FLOAT+TEXT", "PFS: MCS MEB Temp 6"
# 1102, "FLOAT+TEXT", "PFS: MCS MEB Temp 7"
# 1103, "INTEGER+TEXT", "PFS: MCS MEB Power 1"
# 1104, "INTEGER+TEXT", "PFS: MCS MEB Power 2"
# 1105, "INTEGER+TEXT", "PFS: MCS MEB Power 3"
# 1106, "INTEGER+TEXT", "PFS: MCS MEB Power 4"
# 1107, "FLOAT+TEXT", "PFS: MCS MEB Flow"
# 1108, "FLOAT+TEXT", "PFS: MCS MCS CCD Temp"
