actors:
  meb:
    temps: [[0, 1096],        # Get rid of the CHARIS hack below before using.
            [1, 1097],
            [2, 1098],
            [3, 1099],
            [4, 1100],
            [5, 1101],
            [6, 1102]]
    power:
      [[0, 1103],
       [1, 1104],
       [2, 1105],
       [3, 1106]]
    flow: [[0, 1107]]

  dcb:
    atenVAW:
      [[0, 1108],
       [1, 1109],
       [2, 1110]]

  xcu_b1:
    coolerStatus:
      [[0, 1120],
       [2, 1121]]
    coolerTemps:
      [[0, 1122],
       [1, 1123],
       [2, 1124],
       [3, 1125]]
    pressure:
      [[0, 1126]]
    ionpump1:
      [[0, 1127],
       [4, 1128]]
    ionpump2:
      [[0, 1129],
       [4, 1130]]
    ionpump1Errors:
      [[2, 1131]]
    ionpump2Errors:
      [[2, 1132]]
    pcmPower1:
      [[2, 1133]]
    pcmPower2:
      [[2, 1134]]
    temps:
      [[0, 1135],
       [1, 1136],
       [2, 1137],
       [3, 1138],
       [4, 1139],
       [10, 1140],
       [11, 1141]]
    heaters:
      [[4, 1142],
       [5, 1143],
       [6, 1144],
       [7, 1145]]
    gatevalve:
      [[0, 1146],
       [1, 1147]]
    turboSpeed:
      [[0, 1148]]

  xcu_r1:
    coolerStatus:
      [[0, 1150],
       [2, 1151]]
    coolerTemps:
      [[0, 1152],
       [1, 1153],
       [2, 1154],
       [3, 1155]]
    pressure:
      [[0, 1156]]
    ionpump1:
      [[0, 1157],
       [4, 1158]]
    ionpump2:
      [[0, 1159],
       [4, 1160]]
    ionpump1Errors:
      [[2, 1161]]
    ionpump2Errors:
      [[2, 1162]]
    pcmPower1:
      [[2, 1163]]
    pcmPower2:
      [[2, 1164]]
    temps:
      [[0, 1165],
       [1, 1166],
       [2, 1167],
       [3, 1168],
       [4, 1169],
       [10, 1170],
       [11, 1171]]
    heaters:
      [[4, 1172],
       [5, 1173],
       [6, 1174],
       [7, 1175]]
    gatevalve:
      [[0, 1176],
       [1, 1177]]
    turboSpeed:
      [[0, 1178]]

  enu_sm1:
    temps1:
      [[0, 1180],
       [1, 1181],
       [2, 1182],
       [3, 1183],
       [4, 1184],
       [5, 1185],
       [6, 1186],
       [7, 1187],
       [8, 1188],
       [9, 1189]]
    temps2:
      [[0, 1190],
       [1, 1191],
       [2, 1192],
       [3, 1193],
       [4, 1194],
       [5, 1195],
       [6, 1196],
       [7, 1197],
       [8, 1198],
       [9, 1199]]

  tests:
    keytest1:
      [[0, 2010],
       [1, 2011]]
    keytest2:
      [[0, 2012]]
    keytest3:
      [[0, 2013],
       [1, 2014]]





#  mcs:
#    ccdTemp: [[0, 1108]]

# 1096, "FLOAT+TEXT", "PFS: MCS MEB Temp 1"
# 1097, "FLOAT+TEXT", "PFS: MCS MEB Temp 2"
# 1098, "FLOAT+TEXT", "PFS: MCS MEB Temp 3"
# 1099, "FLOAT+TEXT", "PFS: MCS MEB Temp 4"
# 1100, "FLOAT+TEXT", "PFS: MCS MEB Temp 5"
# 1101, "FLOAT+TEXT", "PFS: MCS MEB Temp 6"
# 1102, "FLOAT+TEXT", "PFS: MCS MEB Temp 7"
# 1103, "INTEGER+TEXT", "PFS: MCS MEB Power 1"
# 1104, "INTEGER+TEXT", "PFS: MCS MEB Power 2"
# 1105, "INTEGER+TEXT", "PFS: MCS MEB Power 3"
# 1106, "INTEGER+TEXT", "PFS: MCS MEB Power 4"
# 1107, "FLOAT+TEXT", "PFS: MCS MEB Flow"
# 1108, "FLOAT+TEXT", "PFS: MCS MCS CCD Temp"
