actors:
  charis:
    ionpump1: [[1, 1023],
               [2, 1024],     
               [3, 1026],     
               [4, 1027]]
    temps: [[0, 1013],
            [1, 1014],
            [2, 1015],
            [3, 1016],
            [4, 1017],
            [5, 1018],
            [6, 1019],
            [7, 1020]]
    pressures: [[0, 1000],
                [1, 1001],
                [2, 1002]]
